/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : full-screen-window
 #	author : miyako
 #	2017/01/31
 #
 # --------------------------------------------------------------------------------*/



// --- full-screen-window
void Get_window_full_screen(sLONG_PTR *pResult, PackagePtr pParams);
void SET_WINDOW_FULL_SCREEN(sLONG_PTR *pResult, PackagePtr pParams);
