/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-full-screen.h
 #	source generated by 4D Plugin Wizard
 #	Project : full screen
 #	author : miyako
 #	2024/12/16
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_FULL_SCREEN_H
#define PLUGIN_FULL_SCREEN_H

#include "4DPluginAPI.h"

#if VERSIONMAC
#import <cocoa/cocoa.h>
#import <objc/runtime.h>
#ifndef __LP64__
//or check CGFLOAT_IS_DOUBLE
#define VERSION_MAC_64 0
#define VERSION_MAC_32 1
#else
#define VERSION_MAC_64 1
#define VERSION_MAC_32 0
#endif
#endif

#pragma mark -

void Get_window_full_screen(PA_PluginParameters params);
void SET_WINDOW_FULL_SCREEN(PA_PluginParameters params);

#endif /* PLUGIN_FULL_SCREEN_H */
